type TaskItem {
  id: ID!
  parentColumnId: ID!
  title: String!
  description: String
}

type TasksColumn {
  id: ID!
  title: String!
  tasks: [TaskItem!]!
}

extend type Query {
  tasks: [TaskItem!]!
  columns: [TasksColumn!]!
  task(id: ID!): TaskItem
}